import Head from "next/head";
import Image from "next/image";
import Categories from "../components/Categories";
import Fashion from "../components/Fashion";
import Header from "../components/Header";
import Offers from "../components/Offers";
import Search from "../components/Search";
import TopSellers from "../components/TopSellers";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <div className="p-6">
        <Header />
        <Search />
        <Categories />
        <Offers />
        <Fashion />
        <TopSellers />
      </div>
    </div>
  );
}
